version: '3'
services:
    web:
        build: happy_walker
        command: uwsgi uwsgi.ini
        ports:
        - "8000:8000"
        volumes:
        - ./happy_walker:/data
        depends_on:
          - db
    db:
        image: mongo
        ports:
        - 27017:27017
    
