version: '3'
services:
    web:
        build: happy_walker
        command: python3 manage.py runserver 0.0.0.0:8000
        ports:
        - "8000:8000"
        volumes:
        - ./happy_walker:/data
        depends_on:
          - db
    db:
        image: mongo
        ports:
        - 27017:27017
    test:
         build: happy_walker
         command: python3 manage.py test
         volumes:
         - ./happy_walker:/data
         depends_on:
           - db
           - web

         
