# Generated by Django 2.0.7 on 2018-10-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
