# Generated by Django 2.0.7 on 2018-10-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181003_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauthdata',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='access_token',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='refresh_token',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.DeleteModel(
            name='OAuthData',
        ),
    ]
