# Generated by Django 2.0.7 on 2018-10-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181009_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fitdatamodel',
            options={'ordering': ['-date']},
        ),
    ]
