# Generated by Django 2.0.7 on 2018-10-02 21:03

from django.db import migrations, models
import djongo.models.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180923_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=djongo.models.fields.ListField(default=[]),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=djongo.models.fields.EmbeddedModelField(model_container=users.models.Location, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/avatar.png', upload_to='images/photos'),
        ),
    ]
