# Generated by Django 2.0.7 on 2018-10-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181009_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='refresh_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
