# Generated by Django 2.0.7 on 2018-10-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181009_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
