# Generated by Django 2.0.7 on 2018-10-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181009_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitdatamodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='FitDataModel',
        ),
    ]
