# Generated by Django 2.0.7 on 2018-10-10 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_google_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='google_image',
        ),
    ]
