version: 2
jobs:
  build:
    machine: true
    steps:
    - checkout
    - run: docker-compose build
    - run: docker-compose run --rm web python3 manage.py test
    - run: docker-compose up -d
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
    