version: 2
jobs:
  build_and_test:
    working_directory: ~/python-django
    docker:
      - image: circleci/python:3.6.5
      - image: circleci/mongo:latest
        command: [mongod, --smallfiles]
        # environment:
        #   - MONGO_URL: "mongodb://localhost:27017/data"
    steps: 
      - checkout 
      - restore_cache: 
         key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run: 
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run: # run tests
          command: |
            . venv/bin/activate
            cd happy_walker
            python3 manage.py test
      - store_artifacts: 
          path: test-reports/
          destination: tr1
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build_and_test
      - deploy:
            requires:
            - build_and_test