version: 2
jobs:
  build:
    working_directory: ~/python-django 
    docker:
      - image: circleci/python:3.6.6
      - image: circleci/mongo:latest 
        command: [mongod, --smallfiles]
    steps: 
      - checkout 
      - restore_cache: 
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run: 
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
  test:
    docker:
      - image: circleci/python:3.6.6
      - image: circleci/mongo:latest
    steps:
      - run: # run tests
          command: |
            . venv/bin/activate
            python3 happy_walker/manage.py test
      - store_artifacts: 
          path: test-reports/
          destination: tr1
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - test–Ω:
        requires:
          - build
      - deploy:
          requires:
            - build
            - test        