version: 2
jobs:
  build:
    machine: true
    steps:
    - checkout
    - run: docker-compose build
    - run: docker-compose run --rm web uwsgi --ini uwsgi.ini
    - run: docker-compose up -d
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build        