# Generated by Django 2.0.7 on 2018-10-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiModel',
        ),
        migrations.AlterModelOptions(
            name='fitdatamodel',
            options={'ordering': ['-user']},
        ),
    ]
