# Generated by Django 2.0.7 on 2018-10-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0002_auto_20181011_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitdatamodel',
            name='lol',
            field=models.IntegerField(default=0),
        ),
    ]
